# Visualization

When you analyze data, it is crucial to communicate with simplicity what evidence you found. Therefore, this chapter will focus on how to bring your evidence to your audience.

## Graphs with Python

When you work with Python, there are three main libraries you need to know: 

- `seaborn`, which can plot extremely beautiful graphs, without much efforts. 
- `matplotlib`, for more advanced stuff, this is the library you need to master.
- `plotly`, for implementations into websites. Noob.

### Seaborn

#### Draw a Time-Series (= Line-Chart)

- A line-chart is often used to visualize a trend in the data over time.

```{python, eval = FALSE}
import seabron as sns

sns.lineplot(data = spotify_data)
```

#### Draw a Barplot (= Barchart)

```{python, eval = FALSE}
import seabron as sns

sns.barplot(x = data.Racing, y = data.index)
```

#### Draw a Heatmap

```{python, eval = FALSE}
import seabron as sns

sns.heatmap(data = flight_data, annot = True)
```

#### Draw a Scatterplot (Streudiagramm // Punktwolke)

- You can check, whether you have enough variation in your data to predict the dependent variable. 

##### With 2 variables (incl. regression-line)

```{python, eval = FALSE}
import seabron as sns

sns.scatterplot(x = health_data['bmi'], y = health_data['life_expectancy'])

# include a regression-line:
sns.regplot(x = health_data['bmi'], y = health_data['life_expectancy'])
```

##### With 3 variables, where 2 are `continuous` & 1 is `categorical`

```{python, eval = FALSE}
import seabron as sns

sns.scatterplot(x = health_data['bmi'], y = health_data['life_expectancy'], hue = health_data['smoker'])

# include a regression-line:
sns.lmplot(x = health_data['bmi'], y = health_data['life_expectancy'], hue = health_data['smoker']) # note that it is not the same, as when you used 2 variables!
```

#### Draw a Histogram 

A histogram sorts the data, then it is putting the data into intervalls of data (= batches) and finally counts the frequency those batches occur.

- Useful to check the distribution of the data

> Why should we use this?

For example, in order to see whether our data is normally distributed (= Glockenkurve). 

_By definition - if a variable follows (roughly) a normal distribution - you can standardize the variable._

<mark>If you want to do _Deep Learning_, then a transformation like normalisation (OR standardisation?) is required, that's the reason why we care about the distribution!</mark>

##### Discrete Version

```{python, eval = FALSE}
import seabron as sns

sns.distplot(
a = iris_data['Petal Length (cm)'], # a column you would like to plot
label = "Rose",
kde = False # "Kernel Density Estimate" (kde): always provide this input when creating a histogram
)
```

##### Continuous Version (Kernel Density Estimate)

```{python, eval = FALSE}
import seabron as sns

### ---- Standard KDE-Plot
sns.kdeplot(
data = iris_data['Petal Length (cm)'],
shade = True # colors the area below the curve
)

### ---- 2-Dimensional KDE-Plot, when using more than 1 column
sns.jointplot(
x = iris_data['Petal Length (cm)',
y = iris_data['Septal Width (cm)'],
kind = "kde"
)
```

#### Change Style of different `Seaborn`-Plots

- <u>Key</u>:Set the new style BEFORE you run your code for the actual graph!

```{python, eval = FALSE}
import seabron as sns

### ---- Example for changing the colors // styles with a new style "dark":
sns.set_style("dark") # Possibile styles to choose from: {"darkgrid", "whitegrid", "dark", "white", "ticks"}
```

### Matplotlib

#### Set Width & Height of Graph

```{python, eval=FALSE}
import matplotlib.pyplot as plt

plt.figure(figsize=(10,6)) # 1. width, 2. height
```

#### Set title of Graph

```{python, eval=FALSE}
import matplotlib.pyplot as plt

plt.title('Hello World')
```

#### Set Label of Axes

```{python, eval=FALSE}
import matplotlib.pyplot as plt

plt.ylabel('Average Gaming Score')
plt.xlabel('Date')
```

#### Force Legend to appear

```{python, eval=FALSE}
import matplotlib.pyplot as plt

plt.legend()
```


## Statistics

### The Normal Distribution

_Wir wollen die Normal-Verteilung der Grösse aller Menschen abbilden. Dies ist möglich, wenn wir die Durchschnitts-Grösse $\mu$ & die Standard-Abweichung $\sigma$ der Menschen-Grösse kennen, z.B._:

- $\mu$ = 170cm
- $\sigma$ = 10cm

Diese Werte müssen nun in die **Formel der Normalverteilung** (= Funktion) eingesetzt werden:

$f(x) = \frac{1}{\sigma\sqrt{2\pi}}*e^{-\frac{(x - \mu)^2}{2\sigma^2}}$

```{r normal-distr-plot, echo=FALSE, message=FALSE, warning=FALSE}
# Here I will plot a Graph with ggplot2:


### 1) Load packages & datasets needed:

library(ggplot2)
library(dplyr)
library(gcookbook)

### 2) Plot a function:

my_normaldistr_fun <- function(xvar) {
1 / (10*sqrt(2*3.141593))*(exp(-((xvar-170)^2)/2*100))
} # first, I specify the function

# First, create a dataframe with only 1 variable - e.g. our range of x-values -
# that goes - for example - from 0 to 20 [note that - technically - the command
# x = c(0,20) will only create two values, namely 0 and 20, but NOT the whole
# range of values from 0 to 20!!! However, the code below works anyway!]. Next,
# tell R that you want those numbers 0 & 20 to be plottet on your x-axis -
# -> this is all the code within the 'ggplot()' function:
ggplot(data.frame(x = c(0, 20)), aes(x = x)) +
  stat_function(fun = my_normaldistr_fun, geom = "line") # then, pass the above "user-defined
# function" called 'my_normaldistr_fun' as an input into the function stat_function()
```


<mark>Nun müsste man bloss alle einzelne Werte der Grösse (inkl. $\mu$ & $\sigma$), um die Glockenkurve darstellen zu können</mark>.
