# Business | Die Welt der Unternehmen

In diesem File werde ich alles "business-related" tun, was in Zusammenhang mit Data-Science steht.

## Wörterbuch

### IT &amp; Software-Development

- __"Eine Stroy (mit Daten) haben"__: Damit ist gemeint, dass du einen Erklärungsansatz hast, um z.B. ein "weirdes" Phänomen in den Daten zu erklären.
- __agnostisch__: Im IT-Umfeld hat das Wort agnostisch eine besondere Bedeutung. Es bezieht sich auf etwas, das soweit **verallgemeinert** wird, dass es auch unter verschiedenen Umgebungen funktionieren kann. 
	- <u>Allgemeines Beispiel</u>: Denke an mathematische Formeln, welche nur aus "allgemeinen Variablen" bestehen. 
	- <u>Konkretes Software-Beispiel</u>: Eine Plattform-agnostische Software läuft unter jeder Kombination aus Betriebssystemen und Prozessorarchitekturen.
- __cached__: stored away for future use. 
  - <u>Beispiel</u>: Think of a Browser, which can store - in his memory - the pictures and other HTML, CSS or JS-Files. This allows faster download of these resources, once a user visits a website on a later point in time in the future.
- __Client__: Damit ist häufig der Browser gemeint, wenn er Abfragen an den Server gibt.
- __composite__: custom
- __End to End__: Synonym für "es funktioniert". Hierbei setzt man das Modell mit dem Code auf, führt es aus und man erhält abschliessend einen Output, ohne dass z.B. der Kernel abstürzt (wie es z.B. bei der `AutoARIMA()`-Methode bei `sktime` der Fall war...).

### Organisation

- **<u>Was ist ein _Kanban_?</u>**: In der BWL-Sprache ist *Kanban* **ein Vorgehensmodell** zur Softwareentwicklung.
  - <u>Ziel #1</u>: Das Meetings soll die Anzahl an paralleler Arbeiten, (= **der Work in Progress (WiP)) minimiert // begrenzt werden** und somit kürzere Durchlaufzeiten erreicht.
  - <u>Ziel #2</u>: Das Meeting soll die Probleme – insbesondere **Engpässe – schnell sichtbar machen**.

## Projekt-Management

- **Sitzungen müssen gut dokumentiert werden! Insbesondere ist hervorzuheben, in welche Richtung das Projekt geht.**

## Meetings

> Was ist das Ziel eines Meetings?

Das Ziel des Meetings ist es, dir & deinem Team die **nötige Basis zu geben, damit du in der folgenden Zeit bis zum nächsten Meeting genau weisst, was du zu tun hast**.

Am wichtigsten ist hier mit dem "Boss" zu reden und klar definieren, was er erreichen will im Projekt. Dies gibt die _globale Richtung_ des Projektes an.

_Es ist exterm wichtig, mit dem Boss diese Ziele zu definieren, da die Planung des gesamten Projektes in dieser Phase hier noch definiert werden kann. Nachdem diese anfängliche Gliederung getätigt wurde, kann im Verlauf des Projektes nicht mehr viel davon abgewichen werden. Deshalb hängt die Gesampt-Performance eines Projektes sehr stark von der anfänglichen Planung ab!_

<u>Während</u> des Projektes gibt es dann immer wieder folgende Punkte zu prüfen:

0) Sind die getätigten Schritte im Einklang mit dem Endziel des Bosses? Wichtig ist zu rechtfertigen, was du gerade am tun bist und warum genau du das tust.
1) Aufklärung, damit alle auf dem gleichen Informationsstand sind 
  - <u>Goal</u>: Wo stehen wir? Wie sieht die Situation mit dem Notebook aus?
2) Gibt es noch offene Lücken im Wissen eines Team-Mitglieds, welches von anderen Mitarbeitern gedeckt werden müsste? --> <u>Goal</u>: Kein Mitglied isolieren, jeder muss sich integriert fühlen. Insbesondere Wert auf Papers & Daten setzen hier
3) Was sind weitere offene Optionen und inwiefern eignen sich diese Ansätze für unser Ziel?
    - <u>Goal</u>: Aufzeigen, dass wir noch weitere Alternativen haben, als nur Phillip's Notebooks
4) Sonstige Unklarheiten / Bemerkungen / Inputs / Vorschläge? --> <u>Goal</u>: letzte Informationsasymmetrien beheben.

## Abschluss-Präsentation

- Folgender Aufbau eignet sich:

```
1) Wissenschatlicher ODER unternehmerische Relevanz deines Projektes?
2) Präsentation wichtiger Kernschritte
  - Ziele
  - Methodologie
  - wichtigste Ergebnisse pro Kernschritte
3) Thema a: zum Beispiel Datensammlung
4) Thema b: zum Beispiel Modellierung des "besten Modelles"
5) Thema c: Schlussfolgerungen // Präsentation des MVPs
6) Fragen & Diskussion
```

## Job-Interviews

### Praxis

- <u>Frage des Interviewers</u>: _"Wieso so kompliziert die Webseite deines Vaters? Wenn etwas einfacher geht, sollte es man so machen, nicht?"_ 
  - **<u>Meine Antwort</u>**: „Ja, da haben Sie recht, deshalb habe ich - **in einem späteren Projekt** - meine eigene Webseite mit Hugo kompliert, <mark>was circa 2h geht</mark> ;)
  
### Vorteil von Data-Science Projekten | Punkte, auf die du unbedingt zu Sprechen kommen solltest...

- **<u>Enorm hohes _langfristiges_ Ertrags-Potential</u>**: Sie haben potentiell hohe langfristige Erträge, weil die Modelle - wenn sie nach einem ersten PoC - noch deutlich verbessert werden können.
  - Persistenz-Eigenschaft über die Zeit: das Projekt bleibt bestehen --> keine Sandburg...

### Quellen

- <u>Vorbereitung Data-Science Interviews</u>: [Diese Webseite](https://www.kdnuggets.com/2020/01/data-science-interview-study-guide.html) hat einen kompletten Guide mit Videos / Artikeln zu extrem vielen Key-Concepts gesammelt und zur Verfügung gestellt.