--- 
title: "Data Science from Scratch Code"
author: "Joffrey Anthony"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Computer Set-Up

When building projects *efficiently*, you will need different set-ups in order to have everything in your code work properly, *not only on your own machine, but also on other machines, for example of another team-member*.

## Virtual Environment 

Because the libraries you work with in your projects will be updated over time (this is generally *bad news*, since this will cause all sorts of dependency problems across your libaries you use), it is crucial to understand that you will need a virtual environment (`venv`). There, you will install all the libraries you need. The **major advantage here, is that you can control the version you install the library**. Furthermore, you can send the `venv` to another computer and the people will download exactly the versions of each library. 

<mark>This allows that **your code will <u>always</u> work, independently of the machine you will use**! There will be no dependency problems anymore, which is a huge win.</mark>. :)

### Create a `venv`

Go to your terminal and plug in the following code:

```{terminal}
conda create -n YOUR-VENVIRONMENT-NAME-HERE python=3.6
```

### Activate your newly created `venv`

Weirdly though, you also need to activate the environment you created above. Plug in the following code:

```{terminal}
source activate YOUR-ENVIRONMENT-NAME
```

<mark>**Note that the code above can also be used to activate virtual environments you created in the past**!</mark> =) 